# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9094ed97d14257abd487f2b6ca8c0cc196fd6abbec4da7321008cd61688f1f4b4904048e690313e2b2630542fb1fb955d62de8fd0100553580af841a8c23c408

test:
  secret_key_base: 0e36e1713e63c340786d2a900b50e7f2c2e13a5f7816681faf3f8b1a47edc26fda3578c47474708f8d7046eebba07cbc314092d769d51afdd8011ff7a5593542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
